### Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')
## fetch the first five rows
df.head(5)

         Date Category  Value     Product  Sales Region
0  2026-01-02        A    120      Laptop      5  North
1  2026-01-03        B     85       Mouse     20   East
2  2026-01-04        C    150    Keyboard     15   West
3  2026-01-05        A    220     Monitor      8  South
4  2026-01-06        B     75  Headphones     18  North

In [5]:
df.tail(5)

          Date Category  Value         Product  Sales Region
55  2026-02-26        B     72      Data Cable     27  South
56  2026-02-27        C    160  Network Switch      7  North
57  2026-02-28        A    330   All-in-One PC      3   East
58  2026-03-01        B     95    Portable SSD     10   West
59  2026-03-02        C    215  Gaming Headset      6  South

In [6]:
df.describe()

            Value      Sales
count   60.000000  60.000000
mean   169.833333  10.866667
std     94.386721   7.296311
min     55.000000   2.000000
25%     91.500000   5.000000
50%    147.500000   9.000000
75%    221.250000  15.250000
max    450.000000  30.000000

In [7]:
df.dtypes

Date        object
Category    object
Value        int64
Product     object
Sales        int64
Region      object
dtype: object

In [8]:
## Handling missing Values
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False  False   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False  False    False  False   False
16  False     False  False    False  False   False
17  False     False  False    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False  False    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False  False   False
34  False     False  False    False  False   False
35  False     False  False    False  False   False
36  False     False  False    False  False   False
37  False     False  False    False  False   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False
50  False     False  False    False  False   False
51  False     False  False    False  False   False
52  False     False  False    False  False   False
53  False     False  False    False  False   False
54  False     False  False    False  False   False
55  False     False  False    False  False   False
56  False     False  False    False  False   False
57  False     False  False    False  False   False
58  False     False  False    False  False   False
59  False     False  False    False  False   False

In [10]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
dtype: bool

In [11]:
df.isnull().any()

Date        False
Category    False
Value       False
Product     False
Sales       False
Region      False
dtype: bool

In [12]:
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [13]:
df.fillna(0)

          Date Category  Value              Product  Sales Region
0   2026-01-02        A    120               Laptop      5  North
1   2026-01-03        B     85                Mouse     20   East
2   2026-01-04        C    150             Keyboard     15   West
3   2026-01-05        A    220              Monitor      8  South
4   2026-01-06        B     75           Headphones     18  North
5   2026-01-07        C     95               Webcam     12   East
6   2026-01-08        A    310              Printer      4   West
7   2026-01-09        B     60            USB Drive     30  South
8   2026-01-10        C    140               Router     10  North
9   2026-01-11        A    450               Tablet      6   East
10  2026-01-12        B     55            Mouse Pad     25   West
11  2026-01-13        C    170              Speaker      9  South
12  2026-01-14        A    125           Laptop Bag     14  North
13  2026-01-15        B    200                  SSD      7   East
14  2026-01-16        C     90           Microphone     11   West
15  2026-01-17        A    340            Projector      3  South
16  2026-01-18        B     65           HDMI Cable     28  North
17  2026-01-19        C    130           Power Bank     13   East
18  2026-01-20        A    280        Graphics Card      2   West
19  2026-01-21        B     70              Charger     19  South
20  2026-01-22        C    180          Smart Watch      8  North
21  2026-01-23        A    115            Desk Lamp     16   East
22  2026-01-24        B    145         External HDD      6   West
23  2026-01-25        C     88          Phone Stand     22  South
24  2026-01-26        A    260         Gaming Mouse      7  North
25  2026-01-27        B     98    Wireless Keyboard     10   East
26  2026-01-28        C    210         Office Chair      5   West
27  2026-01-29        A    135         WiFi Adapter     12  South
28  2026-01-30        B    155           CPU Cooler      8  North
29  2026-01-31        C    240  Mechanical Keyboard      4   East
30  2026-02-01        A    320           Smartphone      9   West
31  2026-02-02        B     68              Earbuds     21  South
32  2026-02-03        C    185              Scanner      5  North
33  2026-02-04        A    275               LED TV      3   East
34  2026-02-05        B     92    Bluetooth Speaker     14   West
35  2026-02-06        C    110               Tripod     17  South
36  2026-02-07        A    410       Gaming Console      2  North
37  2026-02-08        B     58              USB Hub     24   East
38  2026-02-09        C    165               Camera      6   West
39  2026-02-10        A    230                Drone      3  South
40  2026-02-11        B     82          Memory Card     18  North
41  2026-02-12        C    195           VR Headset      4   East
42  2026-02-13        A    145     Wireless Charger     11   West
43  2026-02-14        B     74           Stylus Pen     16  South
44  2026-02-15        C    225          NAS Storage      2  North
45  2026-02-16        A    118             Desk Fan     15   East
46  2026-02-17        B    132        Monitor Stand      9   West
47  2026-02-18        C    205        Action Camera      5  South
48  2026-02-19        A    355       Workstation PC      2  North
49  2026-02-20        B     64      Extension Board     20   East
50  2026-02-21        C    155      Wireless Router      8   West
51  2026-02-22        A    290              Mini PC      4  South
52  2026-02-23        B     89         Laptop Stand     13  North
53  2026-02-24        C    175     Document Scanner      6   East
54  2026-02-25        A    245        Smart Display      5   West
55  2026-02-26        B     72           Data Cable     27  South
56  2026-02-27        C    160       Network Switch      7  North
57  2026-02-28        A    330        All-in-One PC      3   East
58  2026-03-01        B     95         Portable SSD     10   West
59  2026-03-02        C    215       Gaming Headset      6  South

In [14]:
## filling missing values with the mean of the column
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

,Date,Category,Value,Product,Sales,Region,Sales_fillNA
0,2026-01-02,A,120,Laptop,5,North,5
1,2026-01-03,B,85,Mouse,20,East,20
2,2026-01-04,C,150,Keyboard,15,West,15
3,2026-01-05,A,220,Monitor,8,South,8
4,2026-01-06,B,75,Headphones,18,North,18
5,2026-01-07,C,95,Webcam,12,East,12
6,2026-01-08,A,310,Printer,4,West,4
7,2026-01-09,B,60,USB Drive,30,South,30
8,2026-01-10,C,140,Router,10,North,10
9,2026-01-11,A,450,Tablet,6,East,6
10,2026-01-12,B,55,Mouse Pad,25,West,25
11,2026-01-13,C,170,Speaker,9,South,9
12,2026-01-14,A,125,Laptop Bag,14,North,14
13,2026-01-15,B,200,SSD,7,East,7
14,2026-01-16,C,90,Microphone,11,West,11
15,2026-01-17,A,340,Projector,3,South,3
16,2026-01-18,B,65,HDMI Cable,28,North,28
17,2026-01-19,C,130,Power Bank,13,East,13
18,2026-01-20,A,280,Graphics Card,2,West,2
19,2026-01-21,B,70,Charger,19,South,19
20,2026-01-22,C,180,Smart Watch,8,North,8
21,2026-01-23,A,115,Desk Lamp,16,East,16
22,2026-01-24,B,145,External HDD,6,West,6
23,2026-01-25,C,88,Phone Stand,22,South,22
24,2026-01-26,A,260,Gaming Mouse,7,North,7
25,2026-01-27,B,98,Wireless Keyboard,10,East,10
26,2026-01-28,C,210,Office Chair,5,West,5
27,2026-01-29,A,135,WiFi Adapter,12,South,12
28,2026-01-30,B,155,CPU Cooler,8,North,8
29,2026-01-31,C,240,Mechanical Keyboard,4,East,4
30,2026-02-01,A,320,Smartphone,9,West,9
31,2026-02-02,B,68,Earbuds,21,South,21
32,2026-02-03,C,185,Scanner,5,North,5
33,2026-02-04,A,275,LED TV,3,East,3
34,2026-02-05,B,92,Bluetooth Speaker,14,West,14
35,2026-02-06,C,110,Tripod,17,South,17
36,2026-02-07,A,410,Gaming Console,2,North,2
37,2026-02-08,B,58,USB Hub,24,East,24
38,2026-02-09,C,165,Camera,6,West,6
39,2026-02-10,A,230,Drone,3,South,3
40,2026-02-11,B,82,Memory Card,18,North,18
41,2026-02-12,C,195,VR Headset,4,East,4
42,2026-02-13,A,145,Wireless Charger,11,West,11
43,2026-02-14,B,74,Stylus Pen,16,South,16
44,2026-02-15,C,225,NAS Storage,2,North,2
45,2026-02-16,A,118,Desk Fan,15,East,15
46,2026-02-17,B,132,Monitor Stand,9,West,9
47,2026-02-18,C,205,Action Camera,5,South,5
48,2026-02-19,A,355,Workstation PC,2,North,2
49,2026-02-20,B,64,Extension Board,20,East,20
50,2026-02-21,C,155,Wireless Router,8,West,8
51,2026-02-22,A,290,Mini PC,4,South,4
52,2026-02-23,B,89,Laptop Stand,13,North,13
53,2026-02-24,C,175,Document Scanner,6,East,6
54,2026-02-25,A,245,Smart Display,5,West,5
55,2026-02-26,B,72,Data Cable,27,South,27
56,2026-02-27,C,160,Network Switch,7,North,7
57,2026-02-28,A,330,All-in-One PC,3,East,3
58,2026-03-01,B,95,Portable SSD,10,West,10
59,2026-03-02,C,215,Gaming Headset,6,South,6

In [15]:
df.dtypes

Date            object
Category        object
Value            int64
Product         object
Sales            int64
Region          object
Sales_fillNA     int64
dtype: object

In [17]:
## Renaming Columns
df = df.rename(columns={'Date' : 'Sale Date'})
df.head()

    Sale Date Category  Value     Product  Sales Region  Sales_fillNA
0  2026-01-02        A    120      Laptop      5  North             5
1  2026-01-03        B     85       Mouse     20   East            20
2  2026-01-04        C    150    Keyboard     15   West            15
3  2026-01-05        A    220     Monitor      8  South             8
4  2026-01-06        B     75  Headphones     18  North            18

In [18]:
## Change datatypes
df['Value_new'] = df['Value'].astype(float)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new
0,2026-01-02,A,120,Laptop,5,North,5,120.0
1,2026-01-03,B,85,Mouse,20,East,20,85.0
2,2026-01-04,C,150,Keyboard,15,West,15,150.0
3,2026-01-05,A,220,Monitor,8,South,8,220.0
4,2026-01-06,B,75,Headphones,18,North,18,75.0

In [19]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2026-01-02,A,120,Laptop,5,North,5,120.0,240
1,2026-01-03,B,85,Mouse,20,East,20,85.0,170
2,2026-01-04,C,150,Keyboard,15,West,15,150.0,300
3,2026-01-05,A,220,Monitor,8,South,8,220.0,440
4,2026-01-06,B,75,Headphones,18,North,18,75.0,150

In [20]:
## Data Aggregating and Grouping
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2026-01-02,A,120,Laptop,5,North,5,120.0,240
1,2026-01-03,B,85,Mouse,20,East,20,85.0,170
2,2026-01-04,C,150,Keyboard,15,West,15,150.0,300
3,2026-01-05,A,220,Monitor,8,South,8,220.0,440
4,2026-01-06,B,75,Headphones,18,North,18,75.0,150

In [21]:
grouped_mean=df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Action Camera          205.0
All-in-One PC          330.0
Bluetooth Speaker       92.0
CPU Cooler             155.0
Camera                 165.0
Charger                 70.0
Data Cable              72.0
Desk Fan               118.0
Desk Lamp              115.0
Document Scanner       175.0
Drone                  230.0
Earbuds                 68.0
Extension Board         64.0
External HDD           145.0
Gaming Console         410.0
Gaming Headset         215.0
Gaming Mouse           260.0
Graphics Card          280.0
HDMI Cable              65.0
Headphones              75.0
Keyboard               150.0
LED TV                 275.0
Laptop                 120.0
Laptop Bag             125.0
Laptop Stand            89.0
Mechanical Keyboard    240.0
Memory Card             82.0
Microphone              90.0
Mini PC                290.0
Monitor                220.0
Monitor Stand          132.0
Mouse                   85.0
Mouse Pad               55.0
NAS Storage            225.0
Network Switch         160.0
Office Chair           210.0
Phone Stand             88.0
Portable SSD            95.0
Power Bank             130.0
Printer                310.0
Projector              340.0
Router                 140.0
SSD                    200.0
Scanner                185.0
Smart Display          245.0
Smart Watch            180.0
Smartphone             320.0
Speaker                170.0
Stylus Pen              74.0
Tablet                 450.0
Tripod                 110.0
USB Drive               60.0
USB Hub                 58.0
VR Headset             195.0
Webcam                  95.0
WiFi Adapter           135.0
Wireless Charger       145.0
Wireless Keyboard       98.0
Wireless Router        155.0
Workstation PC         355.0
Name: Value, dtype: float64

In [23]:
grouped_sum = df.groupby(['Product', 'Region'])['Value'].sum()
print(grouped_sum)

Product              Region
Action Camera        South     205
All-in-One PC        East      330
Bluetooth Speaker    West       92
CPU Cooler           North     155
Camera               West      165
Charger              South      70
Data Cable           South      72
Desk Fan             East      118
Desk Lamp            East      115
Document Scanner     East      175
Drone                South     230
Earbuds              South      68
Extension Board      East       64
External HDD         West      145
Gaming Console       North     410
Gaming Headset       South     215
Gaming Mouse         North     260
Graphics Card        West      280
HDMI Cable           North      65
Headphones           North      75
Keyboard             West      150
LED TV               East      275
Laptop               North     120
Laptop Bag           North     125
Laptop Stand         North      89
Mechanical Keyboard  East      240
Memory Card          North      82
Microphone           West       90
Mini PC              South     290
Monitor              South     220
Monitor Stand        West      132
Mouse                East       85
Mouse Pad            West       55
NAS Storage          North     225
Network Switch       North     160
Office Chair         West      210
Phone Stand          South      88
Portable SSD         West       95
Power Bank           East      130
Printer              West      310
Projector            South     340
Router               North     140
SSD                  East      200
Scanner              North     185
Smart Display        West      245
Smart Watch          North     180
Smartphone           West      320
Speaker              South     170
Stylus Pen           South      74
Tablet               East      450
Tripod               South     110
USB Drive            South      60
USB Hub              East       58
VR Headset           East      195
Webcam               East       95
WiFi Adapter         South     135
Wireless Charger     West      145
Wireless Keyboard    East       98
Wireless Router      West      155
Workstation PC       North     355
Name: Value, dtype: int64

In [24]:
grouped_mean=df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Action Camera          205.0
All-in-One PC          330.0
Bluetooth Speaker       92.0
CPU Cooler             155.0
Camera                 165.0
Charger                 70.0
Data Cable              72.0
Desk Fan               118.0
Desk Lamp              115.0
Document Scanner       175.0
Drone                  230.0
Earbuds                 68.0
Extension Board         64.0
External HDD           145.0
Gaming Console         410.0
Gaming Headset         215.0
Gaming Mouse           260.0
Graphics Card          280.0
HDMI Cable              65.0
Headphones              75.0
Keyboard               150.0
LED TV                 275.0
Laptop                 120.0
Laptop Bag             125.0
Laptop Stand            89.0
Mechanical Keyboard    240.0
Memory Card             82.0
Microphone              90.0
Mini PC                290.0
Monitor                220.0
Monitor Stand          132.0
Mouse                   85.0
Mouse Pad               55.0
NAS Storage            225.0
Network Switch         160.0
Office Chair           210.0
Phone Stand             88.0
Portable SSD            95.0
Power Bank             130.0
Printer                310.0
Projector              340.0
Router                 140.0
SSD                    200.0
Scanner                185.0
Smart Display          245.0
Smart Watch            180.0
Smartphone             320.0
Speaker                170.0
Stylus Pen              74.0
Tablet                 450.0
Tripod                 110.0
USB Drive               60.0
USB Hub                 58.0
VR Headset             195.0
Webcam                  95.0
WiFi Adapter           135.0
Wireless Charger       145.0
Wireless Keyboard       98.0
Wireless Router        155.0
Workstation PC         355.0
Name: Value, dtype: float64

In [26]:
## Aggregate multiple function
grouped_agg = df.groupby('Region')['Value'].agg(['mean', 'sum', 'count'])
grouped_agg

              mean   sum  count
Region
East    175.200000  2628     15
North   175.066667  2626     15
South   156.466667  2347     15
West    172.600000  2589     15

In [28]:
## Merging and joining Dataframes
#Create sample DataFrames
df1 = pd.DataFrame({'key': ['A','B','C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'key': ['A','B','D'], 'Value1': [4,5,6]})

In [29]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [30]:
df2

  key  Value1
0   A       4
1   B       5
2   D       6

In [ ]:
## Merge DataFrames on the 'Key Columns
pd.merge(df1, df2, on="key", how="inner")

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [33]:
pd.merge(df1, df2, on="key", how="outer")

  key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [34]:
pd.merge(df1, df2, on="key", how="left")

  key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [35]:
pd.merge(df1, df2, on="key", how="right")

  key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6