### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in d:\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
## Series
## A Pandas is a one - dimensional array like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
## Create a Series from dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30]
index = ['a','b','c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [8]:
## Dataframe
## Create a Dataframe from a dictionary of list

data = {
    'Name':['Krish', 'Jhon', 'Jack'],
    'Age':[25, 30, 45],
    'City':['Banglore','New York','Florida']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   Jhon   30  New York
2   Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [9]:
import numpy as np
np.array(df)

array([['Krish', 25, 'Banglore'],
       ['Jhon', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [11]:
## Create a Data frame from alist of Dictionaries

data=[
    {'Name': 'Priyanshu', 'Age': 21, 'City': 'Rajgir'},
    {'Name': 'Sonu', 'Age': 21, 'City': 'Simarour'},
    {'Name': 'Sona', 'Age': 21, 'City': 'Faridabaad'}
    
]
df = pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age        City
0  Priyanshu   21      Rajgir
1       Sonu   21    Simarour
2       Sona   21  Faridabaad
<class 'pandas.core.frame.DataFrame'>

In [13]:
df = pd.read_csv('sales_data.csv')
print(df.head(5))

  Transaction ID        Date Product Categories       Product Name  \
0        TXN1001  2026-01-02        Electronics     Wireless Mouse
1        TXN1002  2026-01-03           Clothing        Men T-Shirt
2        TXN1003  2026-01-04          Groceries   Basmati Rice 5kg
3        TXN1004  2026-01-05     Home & Kitchen    Electric Kettle
4        TXN1005  2026-01-06        Electronics  Bluetooth Speaker

   Units Sold  Unit Price  Total Revenue Region Payment Type
0           3         799           2397  North          UPI
1           5         499           2495   East  Credit Card
2           2         699           1398  South         Cash
3           1        1499           1499   West   Debit Card
4           2        1999           3998  North          UPI

In [14]:
df.tail(5)

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1596,West,UPI
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,5999,North,Credit Card
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3597,East,Debit Card
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1745,South,Cash
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,4999,West,UPI

In [16]:
## Accessing Data from DataFrame
df

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type
0,TXN1001,2026-01-02,Electronics,Wireless Mouse,3,799,2397,North,UPI
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2495,East,Credit Card
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1398,South,Cash
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1499,West,Debit Card
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,3998,North,UPI
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2396,East,Credit Card
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1494,South,Cash
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2697,West,UPI
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2796,North,Debit Card
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2598,East,Credit Card
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1592,South,Cash
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2398,West,UPI
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,4999,North,Credit Card
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2397,East,Debit Card
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1745,South,Cash
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,4998,West,UPI
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,3996,North,Credit Card
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4497,East,Debit Card
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,1995,South,Cash
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3499,West,UPI
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2697,North,Credit Card
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1798,East,Debit Card
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1196,South,Cash
23,TXN1024,2026-01-25,Sports,Football,5,699,3495,West,UPI
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,4998,North,Credit Card
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3596,East,Debit Card
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,837,South,Cash
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,5999,West,UPI
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2598,North,Credit Card
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2097,East,Debit Card
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1194,South,Cash
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3598,West,UPI
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4499,North,Credit Card
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3196,East,Debit Card
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,998,South,Cash
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,6999,West,UPI
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,17998,North,Credit Card
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1498,East,Debit Card
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3897,South,Cash
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,5998,West,UPI
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4797,North,Credit Card
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,4998,East,Debit Card
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1796,South,Cash
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8499,West,UPI
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,3998,North,Credit Card
45,TXN1046,2026-02-16,Books,Database Systems,3,649,1947,East,Debit Card
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,1995,South,Cash
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1494,West,UPI
48,TXN1049,2026-02-19,Electronics,Router,2,2999,5998,North,Credit Card
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,3998,East,Debit Card
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1797,South,Cash
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,2999,West,UPI
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,14999,North,Credit Card
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1598,East,Debit Card
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1192,South,Cash
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1596,West,UPI
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,5999,North,Credit Card
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3597,East,Debit Card
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1745,South,Cash
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,4999,West,UPI

In [17]:
df['Product Categories']

0        Electronics
1           Clothing
2          Groceries
3     Home & Kitchen
4        Electronics
5              Books
6             Beauty
7             Sports
8        Electronics
9           Clothing
10         Groceries
11    Home & Kitchen
12       Electronics
13             Books
14            Beauty
15            Sports
16       Electronics
17          Clothing
18         Groceries
19    Home & Kitchen
20       Electronics
21             Books
22            Beauty
23            Sports
24       Electronics
25          Clothing
26         Groceries
27    Home & Kitchen
28       Electronics
29             Books
30            Beauty
31            Sports
32       Electronics
33          Clothing
34         Groceries
35    Home & Kitchen
36       Electronics
37             Books
38            Beauty
39            Sports
40       Electronics
41          Clothing
42         Groceries
43    Home & Kitchen
44       Electronics
45             Books
46            Beauty
47            Sports
48       Electronics
49          Clothing
50         Groceries
51    Home & Kitchen
52       Electronics
53             Books
54            Beauty
55            Sports
56       Electronics
57          Clothing
58         Groceries
59    Home & Kitchen
Name: Product Categories, dtype: object

In [18]:
type(df['Product Categories'])

pandas.core.series.Series

In [19]:
df.loc[0]

Transaction ID               TXN1001
Date                      2026-01-02
Product Categories       Electronics
Product Name          Wireless Mouse
Units Sold                         3
Unit Price                       799
Total Revenue                   2397
Region                         North
Payment Type                     UPI
Name: 0, dtype: object

In [20]:
df.iloc[0]

Transaction ID               TXN1001
Date                      2026-01-02
Product Categories       Electronics
Product Name          Wireless Mouse
Units Sold                         3
Unit Price                       799
Total Revenue                   2397
Region                         North
Payment Type                     UPI
Name: 0, dtype: object

In [21]:
df.loc[0][0]

C:\Users\sonup\AppData\Local\Temp\ipykernel_11020\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'TXN1001'

In [22]:
df.iloc[0][2]

C:\Users\sonup\AppData\Local\Temp\ipykernel_11020\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Electronics'

In [23]:
## Accessing a Specified element

df['Product Categories']

0        Electronics
1           Clothing
2          Groceries
3     Home & Kitchen
4        Electronics
5              Books
6             Beauty
7             Sports
8        Electronics
9           Clothing
10         Groceries
11    Home & Kitchen
12       Electronics
13             Books
14            Beauty
15            Sports
16       Electronics
17          Clothing
18         Groceries
19    Home & Kitchen
20       Electronics
21             Books
22            Beauty
23            Sports
24       Electronics
25          Clothing
26         Groceries
27    Home & Kitchen
28       Electronics
29             Books
30            Beauty
31            Sports
32       Electronics
33          Clothing
34         Groceries
35    Home & Kitchen
36       Electronics
37             Books
38            Beauty
39            Sports
40       Electronics
41          Clothing
42         Groceries
43    Home & Kitchen
44       Electronics
45             Books
46            Beauty
47            Sports
48       Electronics
49          Clothing
50         Groceries
51    Home & Kitchen
52       Electronics
53             Books
54            Beauty
55            Sports
56       Electronics
57          Clothing
58         Groceries
59    Home & Kitchen
Name: Product Categories, dtype: object

In [24]:
df

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type
0,TXN1001,2026-01-02,Electronics,Wireless Mouse,3,799,2397,North,UPI
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2495,East,Credit Card
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1398,South,Cash
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1499,West,Debit Card
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,3998,North,UPI
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2396,East,Credit Card
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1494,South,Cash
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2697,West,UPI
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2796,North,Debit Card
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2598,East,Credit Card
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1592,South,Cash
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2398,West,UPI
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,4999,North,Credit Card
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2397,East,Debit Card
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1745,South,Cash
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,4998,West,UPI
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,3996,North,Credit Card
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4497,East,Debit Card
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,1995,South,Cash
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3499,West,UPI
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2697,North,Credit Card
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1798,East,Debit Card
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1196,South,Cash
23,TXN1024,2026-01-25,Sports,Football,5,699,3495,West,UPI
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,4998,North,Credit Card
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3596,East,Debit Card
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,837,South,Cash
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,5999,West,UPI
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2598,North,Credit Card
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2097,East,Debit Card
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1194,South,Cash
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3598,West,UPI
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4499,North,Credit Card
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3196,East,Debit Card
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,998,South,Cash
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,6999,West,UPI
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,17998,North,Credit Card
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1498,East,Debit Card
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3897,South,Cash
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,5998,West,UPI
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4797,North,Credit Card
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,4998,East,Debit Card
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1796,South,Cash
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8499,West,UPI
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,3998,North,Credit Card
45,TXN1046,2026-02-16,Books,Database Systems,3,649,1947,East,Debit Card
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,1995,South,Cash
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1494,West,UPI
48,TXN1049,2026-02-19,Electronics,Router,2,2999,5998,North,Credit Card
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,3998,East,Debit Card
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1797,South,Cash
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,2999,West,UPI
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,14999,North,Credit Card
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1598,East,Debit Card
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1192,South,Cash
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1596,West,UPI
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,5999,North,Credit Card
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3597,East,Debit Card
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1745,South,Cash
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,4999,West,UPI

In [26]:
df.at[1, 'Product Categories']

'Clothing'

In [27]:
## Accessing a specified elements using iat
df.iat[2,2]

'Groceries'

In [29]:
### Data manipulation with Dataframe
df['Customer']='Sonu'
df

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type,Customer
0,TXN1001,2026-01-02,Electronics,Wireless Mouse,3,799,2397,North,UPI,Sonu
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2495,East,Credit Card,Sonu
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1398,South,Cash,Sonu
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1499,West,Debit Card,Sonu
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,3998,North,UPI,Sonu
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2396,East,Credit Card,Sonu
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1494,South,Cash,Sonu
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2697,West,UPI,Sonu
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2796,North,Debit Card,Sonu
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2598,East,Credit Card,Sonu
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1592,South,Cash,Sonu
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2398,West,UPI,Sonu
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,4999,North,Credit Card,Sonu
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2397,East,Debit Card,Sonu
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1745,South,Cash,Sonu
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,4998,West,UPI,Sonu
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,3996,North,Credit Card,Sonu
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4497,East,Debit Card,Sonu
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,1995,South,Cash,Sonu
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3499,West,UPI,Sonu
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2697,North,Credit Card,Sonu
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1798,East,Debit Card,Sonu
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1196,South,Cash,Sonu
23,TXN1024,2026-01-25,Sports,Football,5,699,3495,West,UPI,Sonu
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,4998,North,Credit Card,Sonu
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3596,East,Debit Card,Sonu
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,837,South,Cash,Sonu
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,5999,West,UPI,Sonu
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2598,North,Credit Card,Sonu
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2097,East,Debit Card,Sonu
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1194,South,Cash,Sonu
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3598,West,UPI,Sonu
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4499,North,Credit Card,Sonu
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3196,East,Debit Card,Sonu
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,998,South,Cash,Sonu
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,6999,West,UPI,Sonu
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,17998,North,Credit Card,Sonu
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1498,East,Debit Card,Sonu
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3897,South,Cash,Sonu
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,5998,West,UPI,Sonu
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4797,North,Credit Card,Sonu
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,4998,East,Debit Card,Sonu
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1796,South,Cash,Sonu
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8499,West,UPI,Sonu
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,3998,North,Credit Card,Sonu
45,TXN1046,2026-02-16,Books,Database Systems,3,649,1947,East,Debit Card,Sonu
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,1995,South,Cash,Sonu
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1494,West,UPI,Sonu
48,TXN1049,2026-02-19,Electronics,Router,2,2999,5998,North,Credit Card,Sonu
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,3998,East,Debit Card,Sonu
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1797,South,Cash,Sonu
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,2999,West,UPI,Sonu
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,14999,North,Credit Card,Sonu
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1598,East,Debit Card,Sonu
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1192,South,Cash,Sonu
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1596,West,UPI,Sonu
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,5999,North,Credit Card,Sonu
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3597,East,Debit Card,Sonu
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1745,South,Cash,Sonu
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,4999,West,UPI,Sonu

In [32]:
## Remove a column
df.drop('Customer', axis=1)

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type
0,TXN1001,2026-01-02,Electronics,Wireless Mouse,3,799,2397,North,UPI
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2495,East,Credit Card
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1398,South,Cash
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1499,West,Debit Card
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,3998,North,UPI
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2396,East,Credit Card
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1494,South,Cash
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2697,West,UPI
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2796,North,Debit Card
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2598,East,Credit Card
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1592,South,Cash
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2398,West,UPI
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,4999,North,Credit Card
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2397,East,Debit Card
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1745,South,Cash
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,4998,West,UPI
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,3996,North,Credit Card
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4497,East,Debit Card
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,1995,South,Cash
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3499,West,UPI
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2697,North,Credit Card
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1798,East,Debit Card
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1196,South,Cash
23,TXN1024,2026-01-25,Sports,Football,5,699,3495,West,UPI
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,4998,North,Credit Card
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3596,East,Debit Card
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,837,South,Cash
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,5999,West,UPI
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2598,North,Credit Card
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2097,East,Debit Card
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1194,South,Cash
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3598,West,UPI
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4499,North,Credit Card
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3196,East,Debit Card
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,998,South,Cash
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,6999,West,UPI
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,17998,North,Credit Card
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1498,East,Debit Card
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3897,South,Cash
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,5998,West,UPI
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4797,North,Credit Card
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,4998,East,Debit Card
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1796,South,Cash
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8499,West,UPI
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,3998,North,Credit Card
45,TXN1046,2026-02-16,Books,Database Systems,3,649,1947,East,Debit Card
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,1995,South,Cash
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1494,West,UPI
48,TXN1049,2026-02-19,Electronics,Router,2,2999,5998,North,Credit Card
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,3998,East,Debit Card
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1797,South,Cash
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,2999,West,UPI
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,14999,North,Credit Card
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1598,East,Debit Card
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1192,South,Cash
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1596,West,UPI
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,5999,North,Credit Card
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3597,East,Debit Card
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1745,South,Cash
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,4999,West,UPI

In [33]:
df

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type,Customer
0,TXN1001,2026-01-02,Electronics,Wireless Mouse,3,799,2397,North,UPI,Sonu
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2495,East,Credit Card,Sonu
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1398,South,Cash,Sonu
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1499,West,Debit Card,Sonu
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,3998,North,UPI,Sonu
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2396,East,Credit Card,Sonu
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1494,South,Cash,Sonu
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2697,West,UPI,Sonu
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2796,North,Debit Card,Sonu
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2598,East,Credit Card,Sonu
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1592,South,Cash,Sonu
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2398,West,UPI,Sonu
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,4999,North,Credit Card,Sonu
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2397,East,Debit Card,Sonu
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1745,South,Cash,Sonu
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,4998,West,UPI,Sonu
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,3996,North,Credit Card,Sonu
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4497,East,Debit Card,Sonu
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,1995,South,Cash,Sonu
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3499,West,UPI,Sonu
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2697,North,Credit Card,Sonu
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1798,East,Debit Card,Sonu
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1196,South,Cash,Sonu
23,TXN1024,2026-01-25,Sports,Football,5,699,3495,West,UPI,Sonu
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,4998,North,Credit Card,Sonu
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3596,East,Debit Card,Sonu
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,837,South,Cash,Sonu
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,5999,West,UPI,Sonu
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2598,North,Credit Card,Sonu
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2097,East,Debit Card,Sonu
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1194,South,Cash,Sonu
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3598,West,UPI,Sonu
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4499,North,Credit Card,Sonu
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3196,East,Debit Card,Sonu
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,998,South,Cash,Sonu
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,6999,West,UPI,Sonu
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,17998,North,Credit Card,Sonu
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1498,East,Debit Card,Sonu
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3897,South,Cash,Sonu
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,5998,West,UPI,Sonu
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4797,North,Credit Card,Sonu
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,4998,East,Debit Card,Sonu
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1796,South,Cash,Sonu
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8499,West,UPI,Sonu
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,3998,North,Credit Card,Sonu
45,TXN1046,2026-02-16,Books,Database Systems,3,649,1947,East,Debit Card,Sonu
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,1995,South,Cash,Sonu
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1494,West,UPI,Sonu
48,TXN1049,2026-02-19,Electronics,Router,2,2999,5998,North,Credit Card,Sonu
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,3998,East,Debit Card,Sonu
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1797,South,Cash,Sonu
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,2999,West,UPI,Sonu
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,14999,North,Credit Card,Sonu
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1598,East,Debit Card,Sonu
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1192,South,Cash,Sonu
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1596,West,UPI,Sonu
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,5999,North,Credit Card,Sonu
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3597,East,Debit Card,Sonu
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1745,South,Cash,Sonu
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,4999,West,UPI,Sonu

In [34]:
df.drop('Customer', axis=1, inplace=True)

In [35]:
df

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type
0,TXN1001,2026-01-02,Electronics,Wireless Mouse,3,799,2397,North,UPI
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2495,East,Credit Card
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1398,South,Cash
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1499,West,Debit Card
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,3998,North,UPI
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2396,East,Credit Card
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1494,South,Cash
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2697,West,UPI
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2796,North,Debit Card
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2598,East,Credit Card
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1592,South,Cash
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2398,West,UPI
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,4999,North,Credit Card
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2397,East,Debit Card
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1745,South,Cash
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,4998,West,UPI
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,3996,North,Credit Card
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4497,East,Debit Card
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,1995,South,Cash
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3499,West,UPI
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2697,North,Credit Card
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1798,East,Debit Card
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1196,South,Cash
23,TXN1024,2026-01-25,Sports,Football,5,699,3495,West,UPI
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,4998,North,Credit Card
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3596,East,Debit Card
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,837,South,Cash
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,5999,West,UPI
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2598,North,Credit Card
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2097,East,Debit Card
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1194,South,Cash
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3598,West,UPI
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4499,North,Credit Card
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3196,East,Debit Card
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,998,South,Cash
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,6999,West,UPI
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,17998,North,Credit Card
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1498,East,Debit Card
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3897,South,Cash
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,5998,West,UPI
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4797,North,Credit Card
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,4998,East,Debit Card
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1796,South,Cash
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8499,West,UPI
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,3998,North,Credit Card
45,TXN1046,2026-02-16,Books,Database Systems,3,649,1947,East,Debit Card
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,1995,South,Cash
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1494,West,UPI
48,TXN1049,2026-02-19,Electronics,Router,2,2999,5998,North,Credit Card
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,3998,East,Debit Card
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1797,South,Cash
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,2999,West,UPI
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,14999,North,Credit Card
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1598,East,Debit Card
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1192,South,Cash
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1596,West,UPI
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,5999,North,Credit Card
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3597,East,Debit Card
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1745,South,Cash
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,4999,West,UPI

In [36]:
## Add Total Revenue to the column

df['Total Revenue'] = df['Total Revenue'] + 100
df

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type
0,TXN1001,2026-01-02,Electronics,Wireless Mouse,3,799,2497,North,UPI
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2595,East,Credit Card
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1498,South,Cash
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1599,West,Debit Card
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,4098,North,UPI
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2496,East,Credit Card
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1594,South,Cash
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2797,West,UPI
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2896,North,Debit Card
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2698,East,Credit Card
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1692,South,Cash
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2498,West,UPI
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,5099,North,Credit Card
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2497,East,Debit Card
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1845,South,Cash
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,5098,West,UPI
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,4096,North,Credit Card
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4597,East,Debit Card
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,2095,South,Cash
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3599,West,UPI
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2797,North,Credit Card
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1898,East,Debit Card
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1296,South,Cash
23,TXN1024,2026-01-25,Sports,Football,5,699,3595,West,UPI
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,5098,North,Credit Card
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3696,East,Debit Card
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,937,South,Cash
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,6099,West,UPI
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2698,North,Credit Card
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2197,East,Debit Card
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1294,South,Cash
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3698,West,UPI
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4599,North,Credit Card
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3296,East,Debit Card
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,1098,South,Cash
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,7099,West,UPI
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,18098,North,Credit Card
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1598,East,Debit Card
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3997,South,Cash
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,6098,West,UPI
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4897,North,Credit Card
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,5098,East,Debit Card
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1896,South,Cash
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8599,West,UPI
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,4098,North,Credit Card
45,TXN1046,2026-02-16,Books,Database Systems,3,649,2047,East,Debit Card
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,2095,South,Cash
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1594,West,UPI
48,TXN1049,2026-02-19,Electronics,Router,2,2999,6098,North,Credit Card
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,4098,East,Debit Card
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1897,South,Cash
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,3099,West,UPI
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,15099,North,Credit Card
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1698,East,Debit Card
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1292,South,Cash
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1696,West,UPI
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,6099,North,Credit Card
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3697,East,Debit Card
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1845,South,Cash
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,5099,West,UPI

In [37]:
df.drop(0, inplace=True)

In [38]:
df

,Transaction ID,Date,Product Categories,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Type
1,TXN1002,2026-01-03,Clothing,Men T-Shirt,5,499,2595,East,Credit Card
2,TXN1003,2026-01-04,Groceries,Basmati Rice 5kg,2,699,1498,South,Cash
3,TXN1004,2026-01-05,Home & Kitchen,Electric Kettle,1,1499,1599,West,Debit Card
4,TXN1005,2026-01-06,Electronics,Bluetooth Speaker,2,1999,4098,North,UPI
5,TXN1006,2026-01-07,Books,Data Science Handbook,4,599,2496,East,Credit Card
6,TXN1007,2026-01-08,Beauty,Face Wash,6,249,1594,South,Cash
7,TXN1008,2026-01-09,Sports,Yoga Mat,3,899,2797,West,UPI
8,TXN1009,2026-01-10,Electronics,USB-C Charger,4,699,2896,North,Debit Card
9,TXN1010,2026-01-11,Clothing,Women's Jeans,2,1299,2698,East,Credit Card
10,TXN1011,2026-01-12,Groceries,Cooking Oil 1L,8,199,1692,South,Cash
11,TXN1012,2026-01-13,Home & Kitchen,Non-Stick Pan,2,1199,2498,West,UPI
12,TXN1013,2026-01-14,Electronics,Smart Watch,1,4999,5099,North,Credit Card
13,TXN1014,2026-01-15,Books,Python Programming,3,799,2497,East,Debit Card
14,TXN1015,2026-01-16,Beauty,Shampoo 500ml,5,349,1845,South,Cash
15,TXN1016,2026-01-17,Sports,Cricket Bat,2,2499,5098,West,UPI
16,TXN1017,2026-01-18,Electronics,Power Bank,4,999,4096,North,Credit Card
17,TXN1018,2026-01-19,Clothing,Hoodie,3,1499,4597,East,Debit Card
18,TXN1019,2026-01-20,Groceries,Tea Powder 1kg,5,399,2095,South,Cash
19,TXN1020,2026-01-21,Home & Kitchen,Mixer Grinder,1,3499,3599,West,UPI
20,TXN1021,2026-01-22,Electronics,Keyboard,3,899,2797,North,Credit Card
21,TXN1022,2026-01-23,Books,Machine Learning Basics,2,899,1898,East,Debit Card
22,TXN1023,2026-01-24,Beauty,Body Lotion,4,299,1296,South,Cash
23,TXN1024,2026-01-25,Sports,Football,5,699,3595,West,UPI
24,TXN1025,2026-01-26,Electronics,Earbuds,2,2499,5098,North,Credit Card
25,TXN1026,2026-01-27,Clothing,Formal Shirt,4,899,3696,East,Debit Card
26,TXN1027,2026-01-28,Groceries,Sugar 5kg,3,279,937,South,Cash
27,TXN1028,2026-01-29,Home & Kitchen,Vacuum Cleaner,1,5999,6099,West,UPI
28,TXN1029,2026-01-30,Electronics,Laptop Stand,2,1299,2698,North,Credit Card
29,TXN1030,2026-01-31,Books,AI Fundamentals,3,699,2197,East,Debit Card
30,TXN1031,2026-02-01,Beauty,Hair Oil,6,199,1294,South,Cash
31,TXN1032,2026-02-02,Sports,Badminton Racket,2,1799,3698,West,UPI
32,TXN1033,2026-02-03,Electronics,External Hard Drive,1,4499,4599,North,Credit Card
33,TXN1034,2026-02-04,Clothing,Track Pants,4,799,3296,East,Debit Card
34,TXN1035,2026-02-05,Groceries,Wheat Flour 10kg,2,499,1098,South,Cash
35,TXN1036,2026-02-06,Home & Kitchen,Air Fryer,1,6999,7099,West,UPI
36,TXN1037,2026-02-07,Electronics,Monitor 24 Inch,2,8999,18098,North,Credit Card
37,TXN1038,2026-02-08,Books,Cloud Computing Guide,2,749,1598,East,Debit Card
38,TXN1039,2026-02-09,Beauty,Perfume,3,1299,3997,South,Cash
39,TXN1040,2026-02-10,Sports,Dumbbell Set,2,2999,6098,West,UPI
40,TXN1041,2026-02-11,Electronics,Webcam,3,1599,4897,North,Credit Card
41,TXN1042,2026-02-12,Clothing,Jacket,2,2499,5098,East,Debit Card
42,TXN1043,2026-02-13,Groceries,Coffee Powder,4,449,1896,South,Cash
43,TXN1044,2026-02-14,Home & Kitchen,Water Purifier,1,8499,8599,West,UPI
44,TXN1045,2026-02-15,Electronics,Gaming Mouse,2,1999,4098,North,Credit Card
45,TXN1046,2026-02-16,Books,Database Systems,3,649,2047,East,Debit Card
46,TXN1047,2026-02-17,Beauty,Sunscreen,5,399,2095,South,Cash
47,TXN1048,2026-02-18,Sports,Skipping Rope,6,249,1594,West,UPI
48,TXN1049,2026-02-19,Electronics,Router,2,2999,6098,North,Credit Card
49,TXN1050,2026-02-20,Clothing,Casual Shoes,2,1999,4098,East,Debit Card
50,TXN1051,2026-02-21,Groceries,Milk Powder,3,599,1897,South,Cash
51,TXN1052,2026-02-22,Home & Kitchen,Induction Cooktop,1,2999,3099,West,UPI
52,TXN1053,2026-02-23,Electronics,Tablet,1,14999,15099,North,Credit Card
53,TXN1054,2026-02-24,Books,Operating Systems,2,799,1698,East,Debit Card
54,TXN1055,2026-02-25,Beauty,Lip Balm,8,149,1292,South,Cash
55,TXN1056,2026-02-26,Sports,Tennis Ball Pack,4,399,1696,West,UPI
56,TXN1057,2026-02-27,Electronics,Graphics Tablet,1,5999,6099,North,Credit Card
57,TXN1058,2026-02-28,Clothing,Sweatshirt,3,1199,3697,East,Debit Card
58,TXN1059,2026-03-01,Groceries,Honey 500g,5,349,1845,South,Cash
59,TXN1060,2026-03-02,Home & Kitchen,Coffee Maker,1,4999,5099,West,UPI

In [40]:
## Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Stastical Summary:\n", df.describe())

Data types:
 Transaction ID        object
Date                  object
Product Categories    object
Product Name          object
Units Sold             int64
Unit Price             int64
Total Revenue          int64
Region                object
Payment Type          object
dtype: object
Stastical Summary:
        Units Sold    Unit Price  Total Revenue
count   59.000000     59.000000      59.000000
mean     2.983051   2068.152542    3705.322034
std      1.716969   2680.698113    2973.725705
min      1.000000    149.000000     937.000000
25%      2.000000    549.000000    1870.500000
50%      3.000000    899.000000    2797.000000
75%      4.000000   2499.000000    4598.000000
max      8.000000  14999.000000   18098.000000

In [43]:
df.describe()

       Units Sold    Unit Price  Total Revenue
count   59.000000     59.000000      59.000000
mean     2.983051   2068.152542    3705.322034
std      1.716969   2680.698113    2973.725705
min      1.000000    149.000000     937.000000
25%      2.000000    549.000000    1870.500000
50%      3.000000    899.000000    2797.000000
75%      4.000000   2499.000000    4598.000000
max      8.000000  14999.000000   18098.000000